export const ADD_INTERVIEWER = 'ADD_INTERVIEWER';
export const EDIT_INTERVIEWER = 'EDIT_INTERVIEWER';
export const DELETE_INTERVIEWER = 'DELETE_INTERVIEWER';

export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const EDIT_CANDIDATE = 'EDIT_CANDIDATE';