export const ADD_INTERVIEWER = 'ADD_INTERVIEWER';
export const EDIT_INTERVIEWER = 'EDIT_INTERVIEWER';
export const DELETE_INTERVIEWER = 'DELETE_INTERVIEWER';

export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const EDIT_CANDIDATE = 'EDIT_CANDIDATE';

export const ADD_SKILLS = 'ADD_SKILLS';
export const EDIT_SKILLS = 'EDIT_SKILLS';

export const SAVE_QUESTIONS = 'SAVE_QUESTIONS';

export const ADD_COMMENT_SUMMARY = 'ADD_COMMENT_SUMMARY';

export const SAVE_INTEVIEW = 'SAVE_INTEVIEW';